services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - '3008:3008'
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`test1.ngocthang.io.vn`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.services.api.loadbalancer.server.port=3008
    networks:
      - coolify

networks:
  coolify:
    external: true